name: CI for php versions
on: ['pull_request', 'push']

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          container:
            - php:8.0
            - php:7.4
            - php:7.3
            - php:7.2
            - php:7.1
            - php:7.0
    container: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install current re2c
        run: |
          apt-get -qy update
          apt-get -qy remove re2c
          apt-get -qy install wget
          wget https://github.com/skvadrik/re2c/releases/download/2.2/re2c-2.2.tar.xz
          tar Jxf re2c-2.2.tar.xz
          cd re2c-2.2; ./configure && make && make install
        working-directory: /tmp
      - name: Install pecl
        if: startsWith(matrix.container, 'php:7')
        run: pecl install vld-beta
      - name: Remove php8 tests on php7
        if: startsWith(matrix.container, 'php:7')
        run: rm -rf src/tests/*php8*/
      - name: Build and run the testsuite
        run: make tests
      - name: Show logs in case of failure
        if: ${{ failure() }}
        run: |
          grep -r . ./src/tests/*/*.out
          grep -r . ./src/tests/*/*.diff
